apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@raze.mx  # Replace with your email
    privateKeySecretRef:
      name: cloudflare-issuer-key
    solvers:
    - dns01:
        cloudflare:
          email: your-email@raze.mx  # Replace with your Cloudflare email
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
